### ISSUE TITLE
Issue with working with Featureviz 

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/featurewiz#101]
from featurewiz import FeatureWiz
fwiz = FeatureWiz(feature_engg = '', nrows=None, transform_target=True, scalers="std",
        		category_encoders="auto", add_missing=False, verbose=0, imbalanced=False, 
                ae_options={}) 
2024-02-01 01:41:12.604946: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-01 01:41:12.605113: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-01 01:41:12.780525: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Imported lazytransform v1.14. 

Imported featurewiz 0.5.4. Use the following syntax:
    >>> wiz = FeatureWiz(feature_engg = '', nrows=None, transform_target=True, scalers="std",
        		category_encoders="auto", add_missing=False, verbose=0. imbalanced=False,
        		ae_options={})
    >>> X_train_selected, y_train = wiz.fit_transform(X_train, y_train)
    >>> X_test_selected = wiz.transform(X_test)
    >>> selected_features = wiz.features
    
featurewiz is given 0.9 as correlation limit...
    Skipping feature engineering since no feature_engg input...
    final list of category encoders given: ['onehot', 'label']
    final list of scalers given: [std]

X_train_selected, y_train = fwiz.fit_transform(X_train, y_train)
X_train_selected
Loaded input data. Shape = (16606, 16)
#### Starting featurewiz transform for train data ####
    Single_Label Multi_Classification problem 
Shape of dataset: (16606, 16). Now we classify variables into different types...
Time taken to define data pipeline = 1 second(s)
No model input given...
Lazy Transformer Pipeline created...
    transformed target from object type to numeric
    Time taken to fit dataset = 1 second(s)
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_33/3698321958.py", line 1, in <module>
    X_train_selected, y_train = fwiz.fit_transform(X_train, y_train)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/featurewiz/featurewiz.py", line 3319, in fit_transform
    X_sel, y_sel = self.transform(X, y)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/featurewiz/featurewiz.py", line 3482, in transform
    X_sel, y_sel = self.lazy.fit_transform(X_sel, y)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lazytransform.py", line 1728, in fit_transform
    X_trans =  self.xformer.transform(X)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/pipeline.py", line 658, in transform
    Xt = transform.transform(Xt)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/pipeline.py", line 658, in transform
    Xt = transform.transform(Xt)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_function_transformer.py", line 238, in transform
    return self._transform(X, func=self.func, kw_args=self.kw_args)
  File "/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_function_transformer.py", line 310, in _transform
    return func(X, **(kw_args if kw_args else {}))
  File "/opt/conda/lib/python3.10/site-packages/lazytransform.py", line 703, in create_column_names_onehot
    Xint = pd.DataFrame(Xt[:,:-num_len], columns = cols_names, dtype=np.int16)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/frame.py", line 816, in __init__
    # ensure correct Manager type according to settings
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 323, in ndarray_to_mgr
    if values.ndim == 1:
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/construction.py", line 625, in sanitize_array
    casted = np.array(data, copy=False)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/construction.py", line 812, in _try_cast
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 1698, in maybe_cast_to_integer_array
    if isinstance(dtype, ExtensionDtype):
ValueError: Trying to coerce float values to integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2144, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1173, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "/opt/conda/lib/python3.10/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
  File "/opt/conda/lib/python3.10/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/conda/lib/python3.10/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/opt/conda/lib/python3.10/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/conda/lib/python3.10/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/opt/conda/lib/python3.10/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/conda/lib/python3.10/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/opt/conda/lib/python3.10/site-packages/executing/executing.py", line 116, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 👍 
Thanks for testing out featurewiz in the Kaggle kernel. As I mentioned in my notebook, you need to restart the Kaggle kernel after pip installing featurewiz. If you don't, you get this weird error called `ValueError: Trying to coerce float values to integers`. Please restart the kernel and run it again after installing and this error will magically vanish!
Thanks again
Auto Vimal
