### ISSUE TITLE
AttributeError: 'int' object has no attribute 'split'

### ISSUE THREAD

**Issue by saskra** [AutoViML/featurewiz#20]
If I try this:

```python
spectra.columns = spectra.columns.astype(str)
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False,
							nrows=None, verbose=2)
X_train_selected = features.fit_transform(spectra, mask_list)
selected_features = features.features 
```

I get this error message:

```shell
Imported DASK version = 0.1.00. nrows=None uses all rows. Set nrows=1000 to randomly sample fewer rows.
output = featurewiz(dataname, target, corr_limit=0.70, verbose=2, sep=',', 
		header=0, test_data='',feature_engg='', category_encoders='',
		dask_xgboost_flag=False, nrows=None)
Create new features via 'feature_engg' flag : ['interactions','groupby','target']
############################################################################################
############       F A S T   F E A T U R E  E N G G    A N D    S E L E C T I O N ! ########
# Be judicious with featurewiz. Don't use it to create too many un-interpretable features! #
############################################################################################
Skipping feature engineering since no feature_engg input...
Skipping category encoding since no category encoders specified in input...
Loading train data...
    Shape of your Data Set loaded: (26717, 788)
    Caution: We will try to reduce the memory usage of dataframe from 80.23 MB
        memory usage after optimization is: 40.16 MB
        decreased by 50.0%
     Loaded. Shape = (26717, 788)
Traceback (most recent call last):
  File "/snap/pycharm-professional/271/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/271/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/saskra/PycharmProjects/bmc/bmc5.py", line 121, in <module>
    X_train_selected = features.fit_transform(spectra, mask_list)
  File "/home/saskra/anaconda3/envs/bmc/lib/python3.9/site-packages/sklearn/base.py", line 855, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/home/saskra/anaconda3/envs/bmc/lib/python3.9/site-packages/featurewiz/featurewiz.py", line 3553, in fit
    features, X_sel = featurewiz(df, target, self.corr_limit, self.verbose, self.sep, 
  File "/home/saskra/anaconda3/envs/bmc/lib/python3.9/site-packages/featurewiz/featurewiz.py", line 1029, in featurewiz
    dataname = remove_special_chars_in_names(dataname, target, verbose=1)
  File "/home/saskra/anaconda3/envs/bmc/lib/python3.9/site-packages/featurewiz/featurewiz.py", line 3586, in remove_special_chars_in_names
    sel_preds = ["_".join(x.split(" ")) for x in sel_preds]
  File "/home/saskra/anaconda3/envs/bmc/lib/python3.9/site-packages/featurewiz/featurewiz.py", line 3586, in <listcomp>
    sel_preds = ["_".join(x.split(" ")) for x in sel_preds]
AttributeError: 'int' object has no attribute 'split'
python-BaseException
```

The first line in my code was already a futile attempt to fix the supposed problem because the original column names in the dataframe were floating point numbers. Can anyone help?

**Comment by AutoViML** [comment]
Hi @saskra 👍 
You made a small mistake when you gave your spectra and mask_list data to featurewiz. As you know, featurewiz requires X_train and y_train to fit and transform. That means spectra and mask_list should not have the same columns i.e. you must have dropped the target from spectra from when you created mask_list. Instead you sent in mask_list and spectra which both had the target column hence you got the error. I have tried to create a clean notebook for you to experiment with with a small sample dataset. Please download it, re-run it and see it makes sense.

[Spectra_Test.zip](https://github.com/AutoViML/featurewiz/files/8124593/Spectra_Test.zip)

Thanks for testing out Featurewiz.
AutoViML team

**Comment by saskra** [comment]
Thanks for trying to explain, but my mask_list/ y_train/ target was never part of spectra/ X_train. Your notebook is running, but when I insert my data, I now get the output: 'float' object has no attribute 'split'.

**Comment by AutoViML** [comment]
Hi @saskra 👍 
It would be very helpful if you can cut and paste 5 rows from your dataset here. It is possible then I can trouble shoot what is so unique about your dataset that's tripping it up. Sorry for the trouble.
It would be even better if you can attach the notebook I gave you with your data snippet.
Thanks
AutoViML

**Comment by saskra** [comment]
Here is a small toy data set:

[small_example_spectra.csv](https://github.com/AutoViML/featurewiz/files/8132844/small_example_spectra.csv)

And here is my script:
```python
import numpy as np
import pandas as pd
from featurewiz import FeatureWiz

df2 = pd.read_csv('small_example_spectra.csv')
y_train = pd.Series(np.random.choice([0, 1], size=(len(df2),)))
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None,
					  verbose=2)
X_train_selected = features.fit_transform(df2, y_train)
```

Thanks a lot for your effort!

**Comment by saskra** [comment]
Here is a small toy data set:

[small_example_spectra.csv](https://github.com/AutoViML/featurewiz/files/8132844/small_example_spectra.csv)

And here is my script:
```python
import numpy as np
import pandas as pd
from featurewiz import FeatureWiz

df2 = pd.read_csv('small_example_spectra.csv')
y_train = pd.Series(np.random.choice([0, 1], size=(len(df2),)))
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None,
					  verbose=2)
X_train_selected = features.fit_transform(df2, y_train)
```

Thanks a lot for your effort!

**Comment by AutoViML** [comment]
Hi @saskra 👍 
Okay I found the problem. I need all the columns in the dataset to have a name. Since your y_train is a pd.Series without a name, it was erroring. You just have to change the code to this and re-run. That should work fine.
```
import numpy as np
import pandas as pd
from featurewiz import FeatureWiz

df2 = pd.read_csv(datapath+filename)
y_train = pd.Series(np.random.choice([0, 1], size=(len(df2),)),name='target')
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None,
					  verbose=2)
X_train_selected = features.fit_transform(df2, y_train)
```

Hope this is helpful.
Thanks
AutoViML

**Comment by saskra** [comment]
Thanks a lot!
